dependencies:
- name: "5"
  repository: http://jenkins-x-chartmuseum:8080
  version: -t
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: timeline
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
